# Generated by Django 4.2.6 on 2023-11-01 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('treated', 'treated')], default='pending', max_length=100)),
                ('category', models.CharField(choices=[('HTML', 'HTML'), ('JS', 'JS'), ('DJANGO', 'DJANGO'), ('NATIVE', 'NATIVE'), ('REACT', 'REACT'), ('NEXT', 'NEXT'), ('GATSBY', 'GATSBY')], default='HTML', max_length=100)),
                ('posteddate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
