# Generated by Django 4.2.6 on 2023-11-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_myimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='coverimages/'),
        ),
    ]
