# Generated by Django 4.2.6 on 2023-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_support_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='client',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='liveurl',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
