# Generated by Django 4.2.6 on 2024-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_support_client_support_liveurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=5000)),
                ('message', models.TextField(blank=True, max_length=5000)),
            ],
        ),
    ]
